# Generated by Django 5.1 on 2024-08-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
